branch-defaults:
  master:
    environment: tinycrit-prod
  staging:
    environmtent: tinycrit-staging
global:
  application_name: tinycrit-api
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-2
  #profile: eb_cli
  sc: git
  workspace_type: Application
